JetBrains/resharper-fsharp

- ReSharper.FSharp/src/FSharp.Psi.Features/src/Formatter/FSharpCodeStylePage.fs
- ReSharper.FSharp/src/FSharp.Psi.Features/src/Formatter/ReformatCode.fs
> [WIP] Added PreserveEndOfLine setting

- ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/FSharpIdentifierTooltipProvider.fs
> Show inferred generic parameters in tooltips

- ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/FSharpIdentifierTooltipProvider.fs
> Show remarks in tooltip

- ReSharper.FSharp/src/FSharp.Psi.Features/src/FileTemplates/FileTemplates.fs
- ReSharper.FSharp/src/FSharp.Psi.Features/src/FileTemplates/FileTemplates.xml
Now F# files will be shown on top of the list:
> Update F# scope names

- ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/FSharpIdentifierTooltipProvider.fs
> Remove "generic parameters:" caption from tooltip

- ReSharper.FSharp/src/FSharp.Psi.Features/src/Formatter/FSharpReformatCode.fs
In the current EAP (6) when you format a piece of code that contains a define, the non-active code will disappear because Fantomas cannot reconstruct it.
For example
becomes 
This PR will use FormatDocument so all code paths are taking into account.
F.ex
> Use FormatDocument is any define is present in the source code.

- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiConsoleRunner.kt
Gradle said that .contentManager is an unresolved link ¯\_(ツ)_/¯
> content manager fix

- ReSharper.FSharp/src/FSharp.Psi/src/Impl/DeclaredElement/ModuleValue.cs
- ReSharper.FSharp/src/FSharp.Psi/src/Impl/Tree/SynPatBase.cs
- ReSharper.FSharp/src/FSharp.Psi/src/Tree/IAsPat.cs
- ReSharper.FSharp/test/data/features/quickFixes/toMutable/LocalAsPat - Pattern matching, not available.fs
- ReSharper.FSharp/test/data/features/quickFixes/toMutable/LocalAsPat - Pattern matching, not available.fs.gold
- ReSharper.FSharp/test/data/features/quickFixes/toMutable/LocalAsPat.fs
- ReSharper.FSharp/test/data/features/quickFixes/toMutable/LocalAsPat.fs.gold
- ReSharper.FSharp/test/data/features/quickFixes/toMutable/TopAsPat.fs
- ReSharper.FSharp/test/data/features/quickFixes/toMutable/TopAsPat.fs.gold
- ReSharper.FSharp/test/src/FSharp.Tests/QuickFixes/ToMutableTest.fs
> To mutable quick fix scope extension

- ReSharper.FSharp/src/FSharp.Psi.Features/src/QuickFixes/RemoveNeverMatchingRuleFix.fs
> Make RemoveNeverMatchingRuleFix scoped

- ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/FSharpIdentifierTooltipProvider.fs
> Add syntax highlighted tooltips

- ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/FSharpIdentifierTooltipProvider.fs
Changes:
- Fixed 'UnknownEntity' being highlighted as a type rather than a value
- Spaces at the start of tooltip lines are no longer ignored
> Tooltip improvements

- rider-fsharp/build.gradle.kts
According to mikhail.philippov, this version contains some essential fix. He didn't dive into too many details, though
> Increase ij gradle plugin version

- ReSharper.FSharp/src/FSharp.Common/src/Checker/FSharpCheckerExtensions.fs
Changes in this PR:
- Don't hit the reactor thread at all when the 'version' hasn't changed. 
- Don't trigger a 2nd typecheck request when the 1st one times out
> Avoid queueing on the reactor for stale typecheck results

- ReSharper.FSharp/src/FSharp.Psi.Features/src/LanguageService/FSharpDeclaredElementIconProvider.fs
- ReSharper.FSharp/test/data/features/icons/Union case class.fs
- ReSharper.FSharp/test/data/features/icons/Union case class.gold
- ReSharper.FSharp/test/data/features/icons/Union case property 01.fs
- ReSharper.FSharp/test/data/features/icons/Union case property 01.gold
- ReSharper.FSharp/test/data/features/icons/Union case property 02 - private.fs
- ReSharper.FSharp/test/data/features/icons/Union case property 02 - private.gold
- ReSharper.FSharp/test/data/features/icons/Union case property 03 - internal.fs
- ReSharper.FSharp/test/data/features/icons/Union case property 03 - internal.gold
- ReSharper.FSharp/test/src/FSharp.Tests/FSharp.Tests.fsproj
- ReSharper.FSharp/test/src/FSharp.Tests/FSharpIconProviderTest.fs
https://youtrack.jetbrains.com/issue/RIDER-55261
> Fix icon for union case

- ReSharper.FSharp/src/FSharp.TypeProvidersProtocol/src/Models/ProxyProvidedNamespace.cs
- rider-fsharp/testData/solutions/TypeProviderLibrary/TypeProviderLibrary/SimpleGenerativeProvider.fs
Fix for https://youtrack.jetbrains.com/issue/RIDER-59965
> TypeProviders: share ProvidedTypeContext between generated types

- ReSharper.FSharp/src/FSharp.Psi.Features/src/QuickFixes/ReplaceWithInterpolatedStringFix.fs
- ReSharper.FSharp/test/data/features/quickFixes/replaceWithInterpolatedString/String 14 - Parentheses required.fs
- ReSharper.FSharp/test/data/features/quickFixes/replaceWithInterpolatedString/String 14 - Parentheses required.fs.gold
- ReSharper.FSharp/test/src/FSharp.Tests/QuickFixes/ReplaceWithInterpolatedStringTest.fs
> Interpolated string quick fix: insert whitespace when necessary 

- ReSharper.FSharp/src/FSharp.TypeProvidersProtocol/src/Utils/ProvidedTypesComparer.cs
- rider-fsharp/src/test/kotlin/typeProviders/TypeProvidersTest.kt
- rider-fsharp/testData/solutions/LegacyTypeProviderLibrary/LegacyTypeProviderLibrary.sln
- rider-fsharp/testData/solutions/LegacyTypeProviderLibrary/TypeProviderLibrary/LegacyTypeProviderLibrary.fsproj
- rider-fsharp/testData/solutions/LegacyTypeProviderLibrary/TypeProviderLibrary/LegacyTypeProviders.fs
- rider-fsharp/testData/solutions/LegacyTypeProviderLibrary/TypeProviderLibrary/Sample.lxml
Fix for https://youtrack.jetbrains.com/issue/RIDER-60909
> TypeProviders: fix ProvidedTypesComparer for old TP SDK

- ReSharper.FSharp/src/FSharp.Psi.Features/src/QuickFixes/AddParensToApplicationFix.fs
- ReSharper.FSharp/test/data/features/quickFixes/addParensToApplication/Type constructor 01 - Union case.fs
- ReSharper.FSharp/test/data/features/quickFixes/addParensToApplication/Type constructor 01 - Union case.fs.gold
- ReSharper.FSharp/test/data/features/quickFixes/addParensToApplication/Type constructor 02 - Exception.fs
- ReSharper.FSharp/test/data/features/quickFixes/addParensToApplication/Type constructor 02 - Exception.fs.gold
- ReSharper.FSharp/test/data/features/quickFixes/addParensToApplication/Type constructor 03 - With lambda application.fs
- ReSharper.FSharp/test/data/features/quickFixes/addParensToApplication/Type constructor 03 - With lambda application.fs.gold
- ReSharper.FSharp/test/src/FSharp.Tests/QuickFixes/AddParensToApplicationTest.fs
https://youtrack.jetbrains.com/issue/RIDER-55427
> AddParensToApplicationFix: support types constructors

- ReSharper.FSharp/src/FSharp.Psi.Features/FSharp.Psi.Features.fsproj
- ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/FSharpQuickDocSuppressor.fs
This PR relies on some changes in the platform, so it can only be merged once my branch there is merged and the changes from it appear in SDK
> Fix RIDER-62618

- ReSharper.FSharp/src/FSharp.Fantomas.Host/FSharp.Fantomas.Host.csproj
- ReSharper.FSharp/src/FSharp.Fantomas.Host/src/FantomasCodeFormatter.cs
Also this will fix 
https://youtrack.jetbrains.com/issue/RIDER-61065
https://youtrack.jetbrains.com/issue/RIDER-61020
> Fantomas: bump version to 4.5.0-beta

- ReSharper.FSharp/src/FSharp.TypeProvidersProtocol/src/TypeProvidersExternalProcess.cs
- rider-fsharp/build.gradle.kts
Backport https://github.com/JetBrains/resharper-fsharp/pull/280/files commit for 211
> Type providers: move launcher from dotnet folder

- rider-fsharp/src/test/kotlin/typeProviders/TypeProvidersRuntimeTest.kt
> Type Providers: fix toolset version in net6 test

- rider-fsharp/build.gradle.kts
https://youtrack.jetbrains.com/issue/IDEA-279019
> Frontend tests: workaround classloader issues

- ReSharper.FSharp/src/FSharp.TypeProviders.Protocol/src/Models/ProxyProvidedType.cs
- ReSharper.FSharp/src/FSharp.TypeProviders.Protocol/src/Models/ProxyProvidedTypeWithContext.cs
> Type providers: implement IRdProvidedEntity for ProxyProvidedTypeWithContext

- ReSharper.FSharp/.idea/.idea.ReSharper.FSharp/.idea/runConfigurations/Rider_Debug_Offline__Unix_.xml
- ReSharper.FSharp/.idea/.idea.ReSharper.FSharp/.idea/runConfigurations/Rider_Debug_Offline__Win_.xml
Same as https://github.com/JetBrains/resharper-fsharp/pull/231 but with ``--offline`` option
> Add Rider offline self debug configurations for the backend solution

- ReSharper.FSharp/src/FSharp.Common/src/Settings/FSharpOptions.fs
- ReSharper.FSharp/src/FSharp.Common/src/Settings/FSharpOptionsPageBase.fs
> FSharpOptionsPage: improve display

- ReSharper.FSharp/src/FSharp.Fantomas.Host/src/FantomasCodeFormatter.cs
- ReSharper.FSharp/src/FSharp.Psi.Features/src/CodeCleanup/FantomasHost.fs
> Fantomas: support format selection

- ReSharper.FSharp/src/FSharp.Psi.Daemon/src/Analyzers/LambdaAnalyzer.fs
- ReSharper.FSharp/src/FSharp.Psi.Features/src/ParameterInfo/FSharpParameterInfo.fs
- ReSharper.FSharp/src/FSharp.Psi.Services/src/Util/FSharpResolveUtil.fs
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Application.fs
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Application.fs.gold
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Delegates - F# 6.fs
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Delegates - F# 6.fs.gold
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Overloads 01.fs
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Overloads 01.fs.gold
- ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Daemon/LambdaAnalyzerTest.fs
Fix for [RIDER-68269](https://youtrack.jetbrains.com/issue/RIDER-68269/False-positive-Lambda-can-be-replaced-with)
> Lambda analyzer: fix for method lambda arguments

- ReSharper.FSharp/src/FSharp.TypeProviders.Host/src/ModelCreators/ProvidedTypeCreator.cs
- ReSharper.FSharp/src/FSharp.TypeProviders.Protocol/src/Models/DummyProvidedExpr.cs
- ReSharper.FSharp/src/FSharp.TypeProviders.Protocol/src/Models/ProxyTypeProvider.cs
- rider-fsharp/src/test/kotlin/typeProviders/TypeProvidersTest.kt
- rider-fsharp/testData/solutions/CsvTypeProvider/CsvTypeProvider.sln
- rider-fsharp/testData/solutions/CsvTypeProvider/TypeProviderLibrary/Library.fs
- rider-fsharp/testData/solutions/CsvTypeProvider/TypeProviderLibrary/TypeProviderLibrary.fsproj
- rider-fsharp/testData/typeProviders/TypeProvidersTest/csvProvider - units of measure/gold/csvProvider - units of measure.gold
Fix for [RIDER-81635](https://youtrack.jetbrains.com/issue/RIDER-81635/Rider-highlights-errors-while-compilation-is-successful)
> Type Providers: fixes for provided units of measure

- ReSharper.FSharp/src/FSharp.Common/src/Util/FSharpPredefinedType.fs
- ReSharper.FSharp/src/FSharp.Psi.Daemon/src/Analyzers/LambdaAnalyzer.fs
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Application.fs
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Application.fs.gold
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Forced calculations.fs
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Forced calculations.fs.gold
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Partial application.fs
- ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Partial application.fs.gold
- ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Daemon/LambdaAnalyzerTest.fs
> LambdaAnalyzer: check for forced calculations

- ReSharper.FSharp/src/FSharp.Common/src/Shim/TypeProviders/TypeProvidersManager.fs
Since we are using a single-threaded protocol to instantiate type providers, we can extend the `ExecuteWithCatch` transaction to ensure that the cache contains already created type providers.
> Type Providers: refactor concurrent type providers instantiation

- ReSharper.FSharp/src/FSharp.Psi.Features/src/Injected/FSharpLiteralInjectionTarget.fs
The main fix will be available in SDK in the next few days.
> Regex/Injections: fix injection in chameleon nodes

- ReSharper.FSharp/src/FSharp.Psi.Intentions/src/Intentions/DataProviders.fs
- ReSharper.FSharp/src/FSharp.Psi.Intentions/src/Intentions/FunctionAnnotationAction.fs
- ReSharper.FSharp/src/FSharp.Psi/src/FSharp.psi
- ReSharper.FSharp/src/FSharp.Psi/src/Impl/Tree/LetOrUseExpr.cs
- ReSharper.FSharp/src/FSharp.Psi/src/Impl/Tree/MatchExpr.cs
- ReSharper.FSharp/src/FSharp.Psi/src/Parsing/ParserMessages.cs
- ReSharper.FSharp/src/FSharp.Psi/src/Tree/IComputableExpr.cs
- ReSharper.FSharp/src/FSharp.Psi/src/Tree/ILetOrUseExpr.cs
- ReSharper.FSharp/src/FSharp.Psi/src/Tree/IMatchExpr.cs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Recursive - Function 01.fs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Recursive - Function 01.fs.gold
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Recursive - Function 02.fs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Recursive - Function 02.fs.gold
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Recursive - Function 03.fs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Recursive - Function 03.fs.gold
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Recursive - Function 04.fs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Recursive - Function 04.fs.gold
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/AndBang - 01.fs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/LetBang - 01.fs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/UseBang - 01.fs
- ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Intentions/SpecifyTypesTest.fs
Allows this intention to also work on recursive bindings.
> Function annotations recursive function

- ReSharper.FSharp/src/FSharp.Psi.Features/FSharp.Psi.Features.fsproj
- ReSharper.FSharp/src/FSharp.Psi.Features/Resources/Strings.Designer.fs
- ReSharper.FSharp/src/FSharp.Psi.Features/Resources/Strings.resx
- ReSharper.FSharp/src/FSharp.Psi.Features/src/CodeCleanup/FSharpReformatCode.fs
[RIDER-89116](https://youtrack.jetbrains.com/issue/RIDER-89116/Not-Localized-Reformat-and-Cleanup-Code-F-Reformat-Code)
> Localization/Backend: localize CodeCleanup page

- ReSharper.FSharp/src/FSharp/FSharp.Psi.Features/FSharp.Psi.Features.fsproj
- ReSharper.FSharp/src/FSharp/FSharp.Psi.Features/src/ZoneMarker.fs
- ReSharper.FSharp/src/FSharp/FSharp.Psi.Features/src/ZoneMarkerServices.fs
This should fix the suspicious project structure
> ZoneMarker: cleanup

- rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/FSharpCommenter.kt
- rider-fsharp/src/main/resources/META-INF/plugin.xml
- rider-fsharp/src/test/kotlin/com/jetbrains/rider/plugins/fsharp/test/cases/FSharpCompletionTest.kt
- rider-fsharp/testData/FSharpCompletionTest/comments - language injections/gold/Program.gold
- rider-fsharp/testData/FSharpCompletionTest/comments - language injections/gold/Program_idea.gold
- rider-fsharp/testData/FSharpCompletionTest/comments - language injections/gold/Program_resharper.gold
- rider-fsharp/testData/FSharpCompletionTest/comments - language injections/source/Program.fs
- rider-fsharp/testData/FSharpCompletionTest/doc comments - not available/gold/Program.gold
- rider-fsharp/testData/FSharpCompletionTest/doc comments - not available/gold/Program_idea.gold
- rider-fsharp/testData/FSharpCompletionTest/doc comments - not available/gold/Program_resharper.gold
- rider-fsharp/testData/FSharpCompletionTest/doc comments - not available/source/Program.fs
> Frontend/completion: support available language injection options

- ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Stages/FcsErrorsStageProcessBase.fs
- ReSharper.FSharp/src/FSharp/FSharp.Psi.Intentions/src/QuickFixes/ConvertTupleToArrayOrListElementsFix.fs
- ReSharper.FSharp/src/FSharp/FSharp.Psi.Intentions/src/QuickFixes/ReplaceReturnTypeFix.fs
- ReSharper.FSharp/src/FSharp/FSharp.Psi.Services/src/Daemon/Highlightings/FcsErrors.xml
- ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/QuickFixes/ReplaceReturnTypeTest.fs
https://github.com/dotnet/fsharp/pull/15840
> FcsErrorsStageProcessBase: use FSharpDiagnosticExtendedData

- ReSharper.FSharp/src/FSharp/FSharp.Psi.Services/src/Daemon/Highlightings/Errors.xml
- ReSharper.FSharp/src/FSharp/FSharp.Psi.Services/src/Daemon/Highlightings/FSharpErrorUtil.fs
- ReSharper.FSharp/src/FSharp/FSharp.Psi/src/FSharp.psi
- ReSharper.FSharp/test/data/features/daemon/recordExprAnalyzer/Availability - Overlap.fs.gold
- ReSharper.FSharp/test/data/features/daemon/recordExprAnalyzer/Availability.fs.gold
- ReSharper.FSharp/test/data/features/quickFixes/useNestedRecordFieldSyntaxFix/Availability - text.fs.gold
> NestedRecordFieldUpdate: improve highlighting range

- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiConsoleRunner.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiInputOutputProcessor.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiProcessHandler.kt
Fix for https://youtrack.jetbrains.com/issue/RIDER-103367/F-interactive-output-is-too-slow-and-suggested-improvements
> Fsi console: fix output rendering perfomance

- rider-fsharp/build.gradle.kts
https://github.com/JetBrains/godot-support/blob/e008595d9baab0c5b722f6055273a6dff21aab75/rider/build.gradle.kts#L88
> Tests/Frontend: add test framework dependency

- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiHost.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiInputOutputProcessor.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/InputSeparatorGutterContentProvider.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/SendProjectReferencesToFsiAction.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/consoleRunners/FsiConsoleRunnerBase.kt
> F# Interactive: show line numbers for the last submit

- ReSharper.FSharp/src/FSharp/FSharp.Psi.Features/src/Fsi/FsiDetector.fs
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiHost.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiInputOutputProcessor.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiProcessHandler.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/consoleRunners/FsiConsoleRunnerBase.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/consoleRunners/FsiScriptProfileConsoleRunner.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/runScript/FSharpScriptConfiguration.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/runScript/FSharpScriptConsoleViewProvider.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/runScript/FSharpScriptExecutorFactory.kt
- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/runScript/FSharpScriptRunProfileState.kt
- rider-fsharp/src/main/resources/META-INF/plugin.xml
> F# Interactive: support debug profile

- rider-fsharp/build.gradle.kts
- rider-fsharp/src/test/kotlin/com/jetbrains/rider/plugins/fsharp/test/cases/typeProviders/BaseTypeProvidersTest.kt
- rider-fsharp/src/test/kotlin/com/jetbrains/rider/plugins/fsharp/test/cases/typeProviders/TypeProvidersFeaturesTest.kt
There's a bunch failing tests, but now at least basic test running mechanism works. Again.
> Fix test compilation and (partially) execution

- ReSharper.FSharp/src/FSharp/FSharp.Common/src/Checker/FcsProjectProvider.fs
Possible fix for https://youtrack.jetbrains.com/issue/RIDER-114924/Referencing-projects-not-invalidated-after-adding-a-new-file
https://github.com/user-attachments/assets/54a1f5ad-38cd-4783-8419-248cb5a21b81
> Project model: fix transitive invalidation when items list changed

- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/runScript/FSharpRunScriptConfigurationProducer.kt
It is still available in file actions
> F# Interactive: hide from intentions list

- ReSharper.FSharp/src/FSharp/FSharp.Common/Resources/Strings.Designer.fs
- ReSharper.FSharp/src/FSharp/FSharp.Common/Resources/Strings.resx
- ReSharper.FSharp/src/FSharp/FSharp.Common/src/Settings/FSharpOptions.fs
- ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/Resources/Strings.Designer.fs
- ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/Resources/Strings.resx
- ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Options/FSharpTypeHintOptionsPage.fs
> FSharpTypeHintsOptionsPage: move pipe hints options

- ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Highlightings/TypeHintHighlighting.fs
- ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Stages/PatternTypeHintsStage.fs
- ReSharper.FSharp/test/data/features/daemon/typeHints/Signatures - Locals 01.fs.gold
- ReSharper.FSharp/test/data/features/daemon/typeHints/Signatures - Show all 01.fs.gold
- ReSharper.FSharp/test/data/features/daemon/typeHints/Signatures - Top level 01.fs.gold
- ReSharper.FSharp/test/data/features/daemon/typeHints/Signatures - Unfinished declarations 01.fs.gold
> Inlay hints/PatternTypeHintsStage: add space after return type

- rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/editorActions/FSharpEnterHandlerDelegate.kt
- rider-fsharp/src/test/kotlin/com/jetbrains/rider/plugins/fsharp/test/cases/typingAssist/FSharpPatchEngineTypingAssists.kt
In respect of https://github.com/JetBrains/resharper-fsharp/commit/9c7465645dd79d8cf0623e7f1464f40f229407af
> Frontend/Typing Assist/Enter: insert newline inside strings

- ReSharper.FSharp/src/FSharp/FSharp.Psi.Intentions/src/Intentions/FunctionAnnotationAction.fs
- ReSharper.FSharp/src/FSharp/FSharp.Psi/src/Tree/ParameterOwnerMemberDeclarationNavigator.cs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Scoped - Parameters 01 - Function.fs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Scoped - Parameters 01 - Function.fs.gold
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Scoped - Parameters 02 - Method.fs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Scoped - Parameters 02 - Method.fs.gold
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Scoped - Parameters 03 - Constructor.fs
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/Scoped - Parameters 03 - Constructor.fs.gold
- ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/Patterns - 02 - Scoped.fs
- ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Intentions/SpecifyTypesTest.fs
> Specify types: add scoped action for parameters
