ReSharper.FSharp/src/FSharp.Common/src/Checker/FSharpOptions.fs
ReSharper.FSharp/src/FSharp.Psi.Features/src/CodeCompletion/FSharpLookupItem.fs

Adds a setting to add 'open' at the top level of the file.  This also sets the default to match with Visual Studio's new default (https://github.com/Microsoft/visualfsharp/pull/5738)
In action:

RIDER-18116: Open at top level when completing out of scope items

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/FSharpTypingAssist.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 01.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 01.fs.gold
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 02.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 02.fs.gold
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 03.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 03.fs.gold
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 04.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 04.fs.gold
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 05.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 05.fs.gold
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 06.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - Surround 06.fs.gold
ReSharper.FSharp/test/src/FSharp.Tests/TypingAssistTest.fs

Fixes RIDER-23963 "Surround Selection on typing brace or parenthesis" has no effect in F#

Implement Surround with braces behavior in typing assist

---

ReSharper.FSharp/src/FSharp.Psi.Features/FSharp.Psi.Features.fsproj
ReSharper.FSharp/src/FSharp.Psi.Features/src/FileTemplates/AzureFSharpScopeProvider.fs
rider-fsharp/src/main/java/com/jetbrains/rider/settings/RiderFSharpFileTemplatesOptionPage.kt
rider-fsharp/src/main/resources/META-INF/plugin.xml

This adds an F#-bound Azure scope (and the corresponding Azure Functions scope point), so the [Azure plugin](https://plugins.jetbrains.com/plugin/11220-azure-toolkit-for-rider) will be able to add the templates there.

Add Azure Functions scope for templates

---

rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiConsoleRunner.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/InputSeparatorGutterContentProvider.kt

Lines were removed from the history view of the interactive console. Now there are only lines above the input text. Added the border to the editor of the console.

Change the Interactive console view

---

rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/SendToFsiActions.kt

This is the last change required to make "Send to FSI" action work in dumb mode (whild indexing).
The dumb-aware intentions (aka Alt-Enter actions) doesn't work in Rider yet, but changes in Rider core are already merging. I expect it to be fully complete in the first EAP.

"Send to FSI" action / intention is now dumb-aware

---

ReSharper.FSharp/src/FSharp.Common/src/Util/RegistryUtil.fs
ReSharper.FSharp/src/FSharp.Psi/src/CodeFormatter/FSharpCodeFormatter.cs
ReSharper.FSharp/src/FSharp.Psi/src/CodeFormatter/FSharpCodeFormatterInfoProvider.cs
ReSharper.FSharp/test/data/features/service/codeFormatter/Local binding indent 01 - No indent.fs
ReSharper.FSharp/test/data/features/service/codeFormatter/Local binding indent 01 - No indent.fs.gold
ReSharper.FSharp/test/data/features/service/codeFormatter/Local binding indent 02 - Correct indent.fs
ReSharper.FSharp/test/data/features/service/codeFormatter/Local binding indent 02 - Correct indent.fs.gold
ReSharper.FSharp/test/data/features/service/codeFormatter/Local binding indent 03 - Big indent.fs
ReSharper.FSharp/test/data/features/service/codeFormatter/Local binding indent 03 - Big indent.fs.gold
ReSharper.FSharp/test/data/features/service/codeFormatter/Nested module indent 01 - No indent.fs
ReSharper.FSharp/test/data/features/service/codeFormatter/Nested module indent 01 - No indent.fs.gold
ReSharper.FSharp/test/data/features/service/codeFormatter/Nested module indent 02 - Correct indent.fs
ReSharper.FSharp/test/data/features/service/codeFormatter/Nested module indent 02 - Correct indent.fs.gold
ReSharper.FSharp/test/data/features/service/codeFormatter/Nested module indent 03 - Big indent.fs
ReSharper.FSharp/test/data/features/service/codeFormatter/Nested module indent 03 - Big indent.fs.gold
ReSharper.FSharp/test/data/features/service/codeFormatter/Top binding indent 01 - No indent.fs
ReSharper.FSharp/test/data/features/service/codeFormatter/Top binding indent 01 - No indent.fs.gold
ReSharper.FSharp/test/data/features/service/codeFormatter/Top binding indent 02 - Correct indent.fs
ReSharper.FSharp/test/data/features/service/codeFormatter/Top binding indent 02 - Correct indent.fs.gold
ReSharper.FSharp/test/data/features/service/codeFormatter/Top binding indent 03 - Big indent.fs
ReSharper.FSharp/test/data/features/service/codeFormatter/Top binding indent 03 - Big indent.fs.gold
ReSharper.FSharp/test/src/FSharp.Tests/FSharp.Tests.fsproj
ReSharper.FSharp/test/src/FSharp.Tests/Service/FSharpCodeFormatterTest.fs
rider-fsharp/protocol/src/kotlin/model/RdFSharpModel.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/FSharpHost.kt
rider-fsharp/src/main/resources/META-INF/plugin.xml

Added some formatter rules for indents inside
- bindings
- nested modules
Also added registry value to enable formatter.

Add indenting formatter rules for bindings and nested module declarations

---

ReSharper.FSharp/src/FSharp.Psi.Features/FSharp.Psi.Features.fsproj

Incorrect capitalisation of `Src` causes the build to try to reference a generated file which doesn't exist - Windows gets away with it by not caring about casing...

Non-Windows platforms care about casing, lowercase is correct in this case

---

ReSharper.FSharp/src/FSharp.Psi.Features/FSharp.Psi.Features.fsproj
ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/FSharpIdentifierTooltipProvider.fs
ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/PipeChainTypeHintStage.fs
ReSharper.FSharp/src/FSharp.Psi.Features/src/FcsReactorMonitor.fs

Show background task in UI when FCS reactor is busy

---

ReSharper.FSharp/src/FSharp.Common/FSharp.Common.fsproj
ReSharper.FSharp/src/FSharp.Common/src/Checker/FSharpCheckerService.fs
ReSharper.FSharp/src/FSharp.Common/src/FcsReactorMonitor.fs
ReSharper.FSharp/src/FSharp.Psi.Features/FSharp.Psi.Features.fsproj
ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/FSharpIdentifierTooltipProvider.fs
ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/PipeChainTypeHintStage.fs
ReSharper.FSharp/src/Services.FSharp/Services.FSharp.csproj
ReSharper.FSharp/src/Services.FSharp/src/ParameterInfo/FSharpParameterInfoContextFactory.cs
ReSharper.FSharp/test/src/FSharp.Common.Tests/FSharp.Common.Tests.fsproj
ReSharper.FSharp/test/src/FSharp.Common.Tests/Stubs.fs
ReSharper.FSharp/test/src/FSharp.Tests/Stubs.fs
rider-fsharp/protocol/src/kotlin/model/RdFSharpModel.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/FSharpHost.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/logs/FSharpLogTraceScenarios.kt
rider-fsharp/src/main/resources/META-INF/plugin.xml

Changes:
- Added registry setting for delay: `rider.fsharp.fcsBusyDelay.ms` (defaults to 5 seconds)
- `onOperationStart` and `onOperationEnd` no longer have to be ran on the main thread
- Added "FcsReactorMonitor" to trace scenarios window. When enabled, slow FSC reactor operations will dump a stack trace of the enqueuing thread (default to 10 seconds)

Reactor monitor improvements

---

ReSharper.FSharp/src/Daemon.FSharp/src/FSharpSymbolHighlightingUtil.cs
ReSharper.FSharp/src/FSharp.Common/src/Util/FSharpSymbolUtil.fs
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Byrefs 01.fs.gold
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Delegates.fs.gold
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Type aliases 01 - Simple types with System dependence.fs
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Type aliases 01 - Simple types with System dependence.fs.gold
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Type aliases 02 - Simple types without System dependence.fs
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Type aliases 02 - Simple types without System dependence.fs.gold
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Type aliases 03 - Units of measure.fs
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Type aliases 03 - Units of measure.fs.gold
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Type aliases 04 - Core abbreviations.fs
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Type aliases 04 - Core abbreviations.fs.gold
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Union case 01.fs.gold
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Units of measure.fs.gold
ReSharper.FSharp/test/src/FSharp.Tests/Daemon/IdentifierHighlightingTest.fs

Improved type abbreviations highlighting: records remain records, structures remain structures etc
Before (Rider 2020.1):
After (Rider 2020.2 with new highlighting options):

Type abbreviations (aliases) highlighting

---

ReSharper.FSharp/src/Daemon.FSharp/src/FSharpSymbolHighlightingUtil.cs
ReSharper.FSharp/src/FSharp.Common/src/Util/FSharpHighlightingAttributeIds.fs
ReSharper.FSharp/src/FSharp.Common/src/Util/FSharpSymbolUtil.fs
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Delegates 01.fs
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Delegates 01.fs.gold
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Delegates 02.fs
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Delegates 02.fs.gold
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Delegates 03.fs
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Delegates 03.fs.gold
ReSharper.FSharp/test/data/features/daemon/identifierHighlighting/Delegates.fs
ReSharper.FSharp/test/src/FSharp.Tests/Daemon/IdentifierHighlightingTest.fs

This PR adds delegate types highlighting.
Types like t = int -> int are now highlighted as delegates
Parameters with such types are now highlighted as functions
Parameters with other delegate signatures are still highlighted as values as they require Invoke(..) call
Before (Rider 2020.1):
After (Rider 2020.2 EAP):

Function types are now highlighted as delegates.

---

rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiConsoleIndicatorRenderer.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiConsoleRunner.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiIcons.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiInputOutputProcessor.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiProcessHandler.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/InputSeparatorGutterContentProvider.kt

Add syntax highlighting and icons to separate input and output to history viewer.

Change history viewer of the interactive console.

---

rider-fsharp/build.gradle.kts

This fixes building on Linux and other case-sensitive platforms. Tested all steps including `runIde` and everything seems to work fine.

Fix building rdgen on case-sensitive filesystems

---

rider-fsharp/build.gradle.kts
rider-fsharp/gradle/wrapper/gradle-wrapper.properties

This is the last step of our long-time struggle with [Kotlin 1.4 migration](https://github.com/JetBrains/rd/pull/143). It will fix most of the tests currently failing in the plugin.

Update to Gradle 6.6, Kotlin 1.4, RdGen 0.203.144

---

.github/workflows/ci.yml
ReSharper.FSharp/test/src/FSharp.Common.Tests/FSharp.Common.Tests.fsproj
ReSharper.FSharp/test/src/FSharp.Tests/FSharp.Tests.fsproj
ReSharper.FSharp/test/src/FSharp.Tests/NavigationTests.fs

PR check examples: 
- failed build: https://github.com/DedSec256/fsharp-support/pull/4
- failed tests:  https://github.com/DedSec256/fsharp-support/pull/3

Add CI for ReSharper.FSharp (Win only)

---

rider-fsharp/build.gradle.kts

The `plugin.xml` file currently doesn't include `<idea-version … />` which is required for using the F# plugin as a dependency (e.g. to add F# support to another Rider plugin). If it is missing, the development version of the IDE used to build the plugin will fail to load the F# plugin.
Resetting the `updateSinceUntilBuild` back to its default value of `true` will add the element into the copy of the file used during build. The gradle scripts will set the current value of the Rider IJ platform as the `since-build` and will use a wildcard for the `until-build`, e.g.:
```xml
<idea-version since-build="203.5949" until-build="203.*" />
```

Generate idea-version during build

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/Intentions/FunctionAnnotationAction.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Caret on let binding.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Caret on let binding.fs.gold
ReSharper.FSharp/test/src/FSharp.Tests/Daemon/ErrorsHighlightingTest.fs
ReSharper.FSharp/test/src/FSharp.Tests/Intentions/SpecifyTypesTest.fs

Execution wasn't consistent with availability - failing test added, fix implemented.
Once this is in I'll update Once this is in, I'll update https://github.com/JetBrains/fsharp-support/pull/202 to target `net211` and fix up any conflicts with this change :+1:.

RIDER-55107: Fix function annotation on let keyword

---

ReSharper.FSharp/src/FSharp.Common/src/Checker/FSharpCheckerExtensions.fs
ReSharper.FSharp/src/FSharp.Common/src/Checker/FSharpCheckerService.fs
ReSharper.FSharp/src/FSharp.ProjectModelBase/src/ProhibitTypeCheckCookie.cs
ReSharper.FSharp/src/FSharp.Psi/src/Impl/Cache2/FSharpCacheProvider.cs

Adds thread-specific cookie to prohibit type checks in critical sections and uses it when creating symbol cache parts.
Makes `FSharpCheckerService.ParseAndCheckFile` the only available API to get type check results in Psi/Psi.Features. Makes this API assert that type checks are allowed.

Allow prohibiting getting type checks via thread-specific cookie

---

ReSharper.FSharp/src/FSharp.Psi/src/Impl/Tree/AccessorDeclaration.cs
ReSharper.FSharp/test/data/cache/csharpResolve/Properties 18 - Explicit accessors - Compiled name.cs
ReSharper.FSharp/test/data/cache/csharpResolve/Properties 18 - Explicit accessors - Compiled name.fs
ReSharper.FSharp/test/data/cache/csharpResolve/Properties 18 - Explicit accessors - Compiled name.gold
ReSharper.FSharp/test/src/FSharp.Tests/Cache/CSharpResolveTest.fs

We should refer to OwnerMember.SourceName because the CompiledName Attribute does not apply to accessor's CompiledName

Use OwnerMember.SourceName in accessor's DeclaredElementName

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/QuickFixes/ReplaceWithWildPatFix.fs
ReSharper.FSharp/src/FSharp.Psi/src/Impl/Cache2/Parts/FSharpGeneratedMethodBase.cs
ReSharper.FSharp/src/FSharp.Psi/src/Impl/DeclaredElement/CompilerGenerated/FSharpGeneratedMemberBase.cs
ReSharper.FSharp/src/FSharp.Psi/src/Impl/DeclaredElement/CompilerGenerated/FSharpGeneratedPropertyBase.cs
ReSharper.FSharp/src/FSharp.Psi/src/Impl/DeclaredElement/CompilerGenerated/FSharpUnionCaseIsCaseProperty.cs
ReSharper.FSharp/src/FSharp.Psi/src/Impl/DeclaredElement/CompilerGenerated/FSharpUnionCaseNewMethod.cs

P.S. 
Also unified the ContainingType declaration through GetContainingType to avoid potential recursive calls in the inheritance hierarchy

Fix for API change (ITypeMember.ContainingType)

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/FSharpIdentifierTooltipProvider.fs

This will fix a trailing `_Rider` from tooltips that use the separator

Use a constant defined in R#

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Stages/FSharpIdentifierTooltipProvider.fs

We need to do this on the F# side because if we do this on the Rider side we'd have to escape all of the tooltips, which would cause us to insert `<br>` tags inside CSS, which totally breaks a lot of tooltips

Escape newlines in tooltips

---

ReSharper.FSharp/.idea/.idea.ReSharper.FSharp/.idea/runConfigurations/Rider_Debug__Unix_.xml
ReSharper.FSharp/.idea/.idea.ReSharper.FSharp/.idea/runConfigurations/Rider_Debug__Win_.xml

@auduchinok, could you check if it works on Mac, please?
Obviously, we could try to do better and create a single configuration for both Unix and Windows (in form of the combined sh/cmd script), but for start, let's check if it works at all :)
(I've tested that on Windows)

Add Rider self debug configurations for the backend solution

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/Daemon/Analyzers/LambdaAnalyzer.fs
ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Id.fs
ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Id.fs.gold
ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Not available.fs
ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Not available.fs.gold

Fix for https://youtrack.jetbrains.com/issue/RIDER-60632
P.S. 
This fix covers only the most common case when the only argument is IUnitPat.

LambdaAnalyzer: fix for call-by-name semantic

---

ReSharper.FSharp/src/FSharp.Fantomas.Protocol/src/FantomasProcess.cs
ReSharper.FSharp/src/FSharp.Fantomas.Protocol/src/FantomasProtocolConstants.cs
ReSharper.FSharp/src/FSharp.TypeProviders.Host/FSharp.TypeProviders.Host.csproj
ReSharper.FSharp/src/FSharp.TypeProviders.Protocol/src/TypeProvidersExternalProcess.cs
ReSharper.FSharp/src/FSharp.TypeProviders.Protocol/src/TypeProvidersProtocolConstants.cs
rider-fsharp/build.gradle.kts

Type providers launchers should not be loaded into the Rider.Backend process, so we need to move them from "dotnet" to a separate folder

Type providers: move launcher from dotnet folder

---

ReSharper.FSharp/src/FSharp.Common/src/Shim/TypeProviders/ExtensionTypingProviderShim.fs
ReSharper.FSharp/src/FSharp.Common/src/Shim/TypeProviders/TypeProvidersManager.fs
rider-fsharp/src/test/kotlin/Extensions.kt
rider-fsharp/src/test/kotlin/typeProviders/TypeProvidersCacheTest.kt

Fixed cases:
1. Concurrent unsynchronized creation of the TypeProvidersConnection, leading to data loss
2. Concurrent creation  of type providers would cause the requested type provider to be missing from the  in-process TypeProvidersCache

Type Providers: fix races in TypeProvidersManager & ExtensionTypingProviderShim

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/Intentions/FunctionAnnotationAction.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/Let bindings - Module 01.fs

Fix for https://youtrack.jetbrains.com/issue/RIDER-67228

FunctionAnnotation: fix returnTypeInfo and check IUnitPat as annotated

---

ReSharper.FSharp/src/FSharp.Psi/src/Features/ParameterInfo/FSharpTypeArgumentCandidate.cs

Fix for https://youtrack.jetbrains.com/issue/RIDER-76221

FSharpTypeArgumentCandidate: fix parameter info for static arguments [WIP]

---

ReSharper.FSharp/src/FSharp.Psi.Services/src/Refactorings/FSharpInlineVariable.fs

I wasn't able to build the `ReSharper.FSharp.sln` without this.

Add missing member SplitDeclarationAndInitializer.

---

rider-fsharp/src/test/kotlin/com/jetbrains/rider/plugins/fsharp/test/Extensions.kt
rider-fsharp/src/test/kotlin/typeProviders/GenerativeTypeProvidersTest.kt
rider-fsharp/src/test/kotlin/typeProviders/TypeProvidersCacheTest.kt
rider-fsharp/src/test/kotlin/typeProviders/TypeProvidersRuntimeTest.kt
rider-fsharp/src/test/kotlin/typeProviders/TypeProvidersSettingTest.kt
rider-fsharp/src/test/kotlin/typeProviders/TypeProvidersTest.kt

Since we host type providers out-of-process by default

Frontend tests/Type Providers: remove 'withOutOfProcessTypeProviders'

---

ReSharper.FSharp/src/FSharp.Psi.Daemon/src/Tooltips/FSharpIdentifierTooltipProvider.fs
ReSharper.FSharp/src/FSharp.TypeProviders.Host/src/ModelCreators/ProvidedCustomAttributeCreator.cs
ReSharper.FSharp/src/FSharp.TypeProviders.Host/src/TypeProvidersContext.cs
ReSharper.FSharp/src/FSharp.TypeProviders.Host/src/Utils/LoggerExtensions.cs
ReSharper.FSharp/src/FSharp.TypeProviders.Protocol/src/Utils/ProvidedCustomAttributeProvider.cs
rider-fsharp/protocol/src/kotlin/model/RdFSharpTypeProvidersModel.kt

There are cases when a type provider may throw an exception when accessing attribute arguments for a provided type/member. Prior to this fix, exceptions were thrown during converting attributes from OOP TP to RD model, which could lead to phantom errors even in cases where FCS does not request attribute arguments. This PR allows exceptions to be thrown not when passing attributes between processes, but when accessing attribute arguments directly.

Type Providers: lazily throw exceptions when accessing attribute arguments

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/CodeCleanup/FSharpReformatCode.fs

Fix for [RIDER-65997](https://youtrack.jetbrains.com/issue/RIDER-65997/Add-F-support-in-Code-Cleanup-options)

Code Cleanup: add F# to Code Cleanup options

---

ReSharper.FSharp/src/FSharp.Psi/src/Impl/DeclaredElement/FSharpMethodParameter.cs
ReSharper.FSharp/test/data/cache/csharpResolve/Parameters 01.cs
ReSharper.FSharp/test/data/cache/csharpResolve/Parameters 01.fs
ReSharper.FSharp/test/data/cache/csharpResolve/Parameters 01.gold
ReSharper.FSharp/test/data/features/parameterInfo/App - Curried - Tuple 17.fs.gold
ReSharper.FSharp/test/data/features/parameterInfo/App - Curried - Tuple 18.fs.gold
ReSharper.FSharp/test/src/FSharp.Tests/Cache/CSharpResolveTest.fs

Fix for [RIDER-80565](https://youtrack.jetbrains.com/issue/RIDER-80565/SystemParamArray-is-not-handled-correctly-when-referencing-from-C-code)
Before:
After:

Psi/FSharpMethodParameter: fix [<ParamArray>] check

---

ReSharper.FSharp/src/FSharp.Psi/src/FSharp.psi

Since we process it as return type info
https://github.com/JetBrains/resharper-fsharp/blob/215b0b4febea04974f01d28555119fa679ad3adc/ReSharper.FSharp/src/FSharp.Psi.Features/src/Parsing/FSharpTreeBuilderBase.fs#L844-L849
https://github.com/JetBrains/resharper-fsharp/blob/215b0b4febea04974f01d28555119fa679ad3adc/ReSharper.FSharp/test/data/parsing/Type%20member%20-%20Abstract%2002%20-%20Function.fs.gold#L18-L36

Psi/AbstractMemberDeclaration: fix typeUsage -> returnTypeInfo

---

ReSharper.FSharp/src/FSharp.Psi/src/FSharp.psi
ReSharper.FSharp/src/FSharp.Psi/src/Impl/Tree/MemberSignature.cs

Similar to https://github.com/JetBrains/resharper-fsharp/pull/392
https://github.com/JetBrains/resharper-fsharp/blob/215b0b4febea04974f01d28555119fa679ad3adc/ReSharper.FSharp/src/FSharp.Psi.Features/src/Parsing/FSharpTreeBuilderBase.fs#L842-L853
https://github.com/JetBrains/resharper-fsharp/blob/215b0b4febea04974f01d28555119fa679ad3adc/ReSharper.FSharp/test/data/parsing/signatures/Type%20member%20-%20Member%2001.fsi.gold#L31-L49

Psi/MemberSignature: fix typeUsage -> returnTypeInfo

---

ReSharper.FSharp/src/FSharp.Psi.Daemon/src/Analyzers/LambdaAnalyzer.fs
ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Implicit conversions.fs
ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Implicit conversions.fs.gold
ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Daemon/LambdaAnalyzerTest.fs

Fix for [RIDER-78171](https://youtrack.jetbrains.com/issue/RIDER-78171/Lambda-can-be-simplified-lead-to-errors)

LambdaAnalyzer: check for implicit conversions

---

ReSharper.FSharp/src/FSharp.Psi.Intentions/src/QuickFixes/ConvertTupleToArrayOrListElementsFix.fs
ReSharper.FSharp/test/data/features/quickFixes/convertTupleToArrayOrListElements/Array 02.fs
ReSharper.FSharp/test/data/features/quickFixes/convertTupleToArrayOrListElements/Array 02.fs.gold
ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/QuickFixes/ConvertTupleToArrayOrListElementsFixTest.fs

Improvement for
https://youtrack.jetbrains.com/issue/RIDER-70854/Improve-Use-separators-quickfix

ConvertTupleToArrayOrListElementsFix: improvement for 'a * 'b

---

ReSharper.FSharp/src/FSharp.Psi.Daemon/src/Analyzers/LambdaAnalyzer.fs
ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Optional parameters.fs
ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Optional parameters.fs.gold
ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Daemon/LambdaAnalyzerTest.fs

Fix for [RIDER-87136](https://youtrack.jetbrains.com/issue/RIDER-87136/False-positive-simplify-lambda)

LambdaAnalyzer: disable for invocations with optional args

---

ReSharper.FSharp/src/FSharp.Fantomas.Host/FSharp.Fantomas.Host.csproj
ReSharper.FSharp/src/FSharp.TypeProviders.Host.NetCore/FSharp.TypeProviders.Host.NetCore.csproj

Since v5.x.x has [vulnerability](https://devhub.checkmarx.com/cve-details/CVE-2021-31957/?utm_source=jetbrains&utm_medium=referral&utm_campaign=rider&utm_term=nuget)

Bump Microsoft.NETCore.Platform

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/Parsing/FSharpImplTreeBuilder.fs
ReSharper.FSharp/src/FSharp.Psi/src/FSharp.psi
ReSharper.FSharp/test/data/parsing/Type member - Let bindings - Extern 01.fs
ReSharper.FSharp/test/data/parsing/Type member - Let bindings - Extern 01.fs.gold
ReSharper.FSharp/test/data/parsing/Type member - Let bindings - Multiple 01.fs
ReSharper.FSharp/test/data/parsing/Type member - Let bindings - Multiple 01.fs.gold
ReSharper.FSharp/test/src/FSharp.Tests/Parsing/FSharpParserTest.fs

Fix for [RIDER-88948](https://youtrack.jetbrains.com/issue/RIDER-88948/Highlighting-is-broken-in-F-file)

Psi/Tree builder: support extern declarations in type members

---

ReSharper.FSharp/src/FSharp.Fantomas.Host/src/FantomasCodeFormatter.cs
ReSharper.FSharp/src/FSharp.Fantomas.Host/src/FantomasEndPoint.cs
ReSharper.FSharp/src/FSharp.Psi.Features/src/CodeCleanup/FSharpReformatCode.fs
ReSharper.FSharp/src/FSharp.Psi.Features/src/CodeCleanup/FantomasHost.fs
rider-fsharp/protocol/src/kotlin/model/RdFantomasModel.kt
rider-fsharp/src/test/kotlin/com/jetbrains/rider/plugins/fsharp/test/cases/fantomas/FantomasRunOptionsTest.kt
rider-fsharp/testData/fantomas/FantomasRunOptionsTest/local tool 6_0 with cursor/gold/local tool 6_0 with cursor.gold
rider-fsharp/testData/fantomas/FantomasRunOptionsTest/local tool 6_0 with cursor/source/LargeFile.fs

https://github.com/fsprojects/fantomas/issues/2727

Fantomas: support cursor api

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/Internal/FSharpInternalActionGroup.fs

Second part for #487: "Dump current FCS file"
I'm getting the same output as in the `FSharpParserTest._` test:
As it also works for other file types, I'm not sure about the placement in the menu tree.

Add new internal action to dump the PSI of an F# file

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/Parsing/FSharpImplTreeBuilder.fs
ReSharper.FSharp/test/data/parsing/Pattern - Named args 01.fs.gold
ReSharper.FSharp/test/data/parsing/Pattern - Named args 02 - Multiple.fs.gold
ReSharper.FSharp/test/data/parsing/Pattern - Parameters owner 06 - NamedUnionCaseFieldsPat.fs
ReSharper.FSharp/test/data/parsing/Pattern - Parameters owner 06 - NamedUnionCaseFieldsPat.fs.gold
ReSharper.FSharp/test/src/FSharp.Tests/Parsing/FSharpParserTest.fs

Should include the right paren in INamedUnionCaseFieldsPat.

Consider full range when closing NAMED_UNION_CASE_FIELDS_PAT.

---

ReSharper.FSharp/src/FSharp.Psi.Daemon/src/Analyzers/LambdaAnalyzer.fs
ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Not available.fs
ReSharper.FSharp/test/data/features/daemon/lambdaAnalyzer/Not available.fs.gold

fix for [RIDER-91110](https://youtrack.jetbrains.com/issue/RIDER-91110/Wrong-hint-to-remove-lambda-when-passing-active-pattern-case-in-a-function)

LambdaAnalyzer: disable for active patterns

---

RELEASE_NOTES.md

Correct spelling of "dynamic" and "analysis" in 2023.1 release notes

Correct spelling in RELEASE_NOTES.md for version 2023.1

---

ReSharper.FSharp/src/FSharp.Common/FSharp.Common.fsproj
ReSharper.FSharp/src/FSharp.Common/src/Util/XmlDocUtil.fs
ReSharper.FSharp/src/FSharp.Psi.Daemon/FSharp.Psi.Daemon.fsproj
ReSharper.FSharp/src/FSharp.Psi.Daemon/src/Analyzers/XmlDocAnalyzer.fs
ReSharper.FSharp/src/FSharp.Psi.Daemon/src/Stages/FSharpSyntaxHighlightingStage.fs
ReSharper.FSharp/src/FSharp.Psi.Daemon/src/Stages/ZoneMarker.fs
ReSharper.FSharp/src/FSharp.Psi.Daemon/src/Syntax/XmlDocSummaryHighlightingVisitor.fs
ReSharper.FSharp/test/data/features/daemon/syntaxHighlighting/xmlDoc/XmlDoc 01 - Simple summary doc.fs
ReSharper.FSharp/test/data/features/daemon/syntaxHighlighting/xmlDoc/XmlDoc 01 - Simple summary doc.fs.gold
ReSharper.FSharp/test/data/features/daemon/syntaxHighlighting/xmlDoc/XmlDoc 02.fs
ReSharper.FSharp/test/data/features/daemon/syntaxHighlighting/xmlDoc/XmlDoc 02.fs.gold
ReSharper.FSharp/test/src/FSharp.Intentions.Tests/FSharp.Intentions.Tests.fsproj
ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Daemon/XmlDocSyntaxHighlightingTest.fs
ReSharper.FSharp/test/src/FSharp.Tests.Common/src/ZoneMarker.fs

https://github.com/JetBrains/resharper-fsharp/pull/480

XmlDoc: do not highlight tags similar to operators

---

rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/FSharpElements.kt
rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/FSharpStringElementManipulator.kt
rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/FSharpStringExpressionUtils.kt
rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/FSharpWebReferenceContributor.kt
rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/impl/FSharpElementTypes.kt
rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/impl/FSharpInterpolatedStringLiteralExpressionImpl.kt
rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/impl/FSharpInterpolatedStringLiteralExpressionPartImpl.kt
rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/impl/FSharpStringLiteralExpressionBase.kt
rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/impl/StringLiteralExpressionImpl.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/actions/FSharpActionSupportPolicy.kt
rider-fsharp/src/main/resources/META-INF/plugin.xml
rider-fsharp/src/test/kotlin/com/jetbrains/rider/plugins/fsharp/test/cases/markup/injections/UrlInStringsTest.kt
rider-fsharp/testData/markup/injections/UrlInStringsTest/simple/gold/Program.gold
rider-fsharp/testData/markup/injections/UrlInStringsTest/simple/source/Program.fs

Frontend: support URL navigation in string literals

---

ReSharper.FSharp/src/FSharp.Common/src/Settings/FSharpOptionsPageBase.fs

Hi @auduchinok, I needed to add these type annotations to build the `net232` branch locally.
Does this ring a bell?

Add type annotations for rich text.

---

ReSharper.FSharp/src/FSharp.Psi.Services/src/Generate/GenerateProvider.fs
ReSharper.FSharp/test/data/features/generate/overrides/Anchor - Repr 13.fs.gold
ReSharper.FSharp/test/data/features/generate/overrides/Anchor - Repr 19.fs.gold
ReSharper.FSharp/test/data/features/generate/overrides/Anchor - Repr 21.fs
ReSharper.FSharp/test/data/features/generate/overrides/Anchor - Repr 21.fs.gold
ReSharper.FSharp/test/data/features/generate/overrides/Anchor - Repr 23.fs
ReSharper.FSharp/test/data/features/generate/overrides/Anchor - Repr 23.fs.gold
ReSharper.FSharp/test/data/features/generate/overrides/Anchor - Repr 24.fs
ReSharper.FSharp/test/data/features/generate/overrides/Anchor - Repr 24.fs.gold
ReSharper.FSharp/test/src/FSharp.Tests/Generate/FSharpGenerateOverridesTest.fs

This moves the anchor to the last let binding in an IObjectModelTypeRepresentation if there is any.

Place generated override after any let binding in IObjectModelTypeRepresentation

---

ReSharper.FSharp/src/FSharp.Psi.Features/src/CodeCompletion/FSharpCodeCompletionContext.fs
ReSharper.FSharp/src/FSharp.Psi.Features/src/LanguageService/FSharpElementFactory.fs
ReSharper.FSharp/src/FSharp.Psi.Features/src/LanguageService/FSharpLanguageService.fs
ReSharper.FSharp/src/FSharp.Psi.Features/src/Parsing/FSharpParser.fs
ReSharper.FSharp/src/FSharp.Psi.Features/src/Parsing/FSharpSigTreeBuilder.fs
ReSharper.FSharp/src/FSharp.Psi/src/FSharp.psi
ReSharper.FSharp/src/FSharp.Psi/src/IFSharpElementFactory.cs
ReSharper.FSharp/src/FSharp.Psi/src/IFSharpLanguageService.cs
ReSharper.FSharp/src/FSharp.Psi/src/Tree/IGlobalNamespaceDeclaration.cs
ReSharper.FSharp/test/data/parsing/signatures/Nested Module 01.fsi
ReSharper.FSharp/test/data/parsing/signatures/Nested Module 01.fsi.gold
ReSharper.FSharp/test/data/parsing/signatures/_.fsi
ReSharper.FSharp/test/src/FSharp.Tests/Parsing/FSharpParserTest.fs

Extracted the grammar and parser changes from https://github.com/JetBrains/resharper-fsharp/pull/481

Signature tweak to the grammar.

---

ReSharper.FSharp/src/FSharp.Psi.Services/src/Generate/GenerateProvider.fs
ReSharper.FSharp/test/data/features/generate/overrides/Repr - Union - No bar - Single 03.fs
ReSharper.FSharp/test/data/features/generate/overrides/Repr - Union - No bar - Single 03.fs.gold
ReSharper.FSharp/test/data/features/generate/overrides/Repr - Union - No bar - Single 04.fs
ReSharper.FSharp/test/data/features/generate/overrides/Repr - Union - No bar - Single 04.fs.gold
ReSharper.FSharp/test/src/FSharp.Tests/Generate/FSharpGenerateOverridesTest.fs

Single case unions like "type U = C" are interpreted as ITypeAbbreviationRepresentation.
So this PR adds the needed code to add a `|` in front and to fix the indentation.

Fix overrides generation for "naked" single case unions

---

rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/psi/FSharpStringElementManipulator.kt
rider-fsharp/src/test/kotlin/com/jetbrains/rider/plugins/fsharp/test/cases/markup/injections/InjectionEscapersTest.kt
rider-fsharp/testData/markup/injections/InjectionEscapersTest/backslash - simple/gold/backslash - simple.gold
rider-fsharp/testData/markup/injections/InjectionEscapersTest/backslash - simple/source/Program.fs
rider-fsharp/testData/markup/injections/InjectionEscapersTest/backslash at the end - regular/gold/backslash at the end - regular.gold
rider-fsharp/testData/markup/injections/InjectionEscapersTest/backslash at the end - regular/source/Program.fs
rider-fsharp/testData/markup/injections/InjectionEscapersTest/backslash at the end - triple quoted/gold/backslash at the end - triple quoted.gold
rider-fsharp/testData/markup/injections/InjectionEscapersTest/backslash at the end - triple quoted/source/Program.fs
rider-fsharp/testData/markup/injections/InjectionEscapersTest/backslash at the end - verbatim/gold/backslash at the end - verbatim.gold
rider-fsharp/testData/markup/injections/InjectionEscapersTest/backslash at the end - verbatim/source/Program.fs
rider-fsharp/testData/markup/injections/InjectionEscapersTest/backslash before hole - interpolated/gold/backslash before hole - interpolated.gold
rider-fsharp/testData/markup/injections/InjectionEscapersTest/backslash before hole - interpolated/source/Program.fs
rider-fsharp/testData/markup/injections/InjectionEscapersTest/escaped backslash at the end - regular/gold/escaped backslash at the end - regular.gold
rider-fsharp/testData/markup/injections/InjectionEscapersTest/escaped backslash at the end - regular/source/Program.fs

Currently, we don't escape backslashes at the end of the string part (regular or regular interpolated) that will lead to a parsing error in the corresponding F# string. 
Correct escaping examples:

Language injections: fix backslash escaping at the end of the string part

---

ReSharper.FSharp/src/FSharp.Psi/src/FSharp.psi

To align with https://github.com/dotnet/fsharp/blob/8eada0e8c6e28f077899b6757dba16f2dcfddbb8/src/Compiler/pars.fsy#L728

Align bindingSignature with pars.fsy grammar rule.

---

ReSharper.FSharp/src/FSharp.Psi/src/Impl/FSharpArgumentsOwnerUtil.cs
ReSharper.FSharp/test/data/features/daemon/regexp/Detection 01.fs
ReSharper.FSharp/test/data/features/daemon/regexp/Detection 01.fs.gold

Fix for [RIDER-96778](https://youtrack.jetbrains.com/issue/RIDER-96778/StringSyntax-ignored-if-subsequent-optional-parameter-is-left-out)

Language Injections/Regex: fix detection for signatures with optional args

---

ReSharper.FSharp/src/FSharp/FSharp.Psi.Features/src/FSharpTypingAssist.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - bar - disabled.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - bar - disabled.fs.gold
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - left angle - disabled.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - left angle - disabled.fs.gold
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - quotation - disabled.fs
ReSharper.FSharp/test/data/features/service/typingAssist/Brackets - quotation - disabled.fs.gold
ReSharper.FSharp/test/src/FSharp.Tests/Actions/TypingAssistTest.fs

https://youtrack.jetbrains.com/issue/RIDER-106858/Pipe-is-incorrectly-added-to-closing-bracket-when-entering-F-array

Typing assist: respect the 'Auto-insert pair brackets' setting more

---

rider-fsharp/src/main/resources/META-INF/plugin.xml
rider-fsharp/src/main/resources/intellij.rider.plugins.fsharp.injections.xml

The plugin no longer has a strong dependency on IntelliLang. All the injection-dependent stuff has been moved to an optional v2 module.

Fix RIDER-96095: decouple the plugin from IntelliLang

---

rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/SendToFsiActions.kt

Fix for https://youtrack.jetbrains.com/issue/RIDER-107488/Send-to-F-Interactive-is-not-available-for-not-indexed-script-file
Overrides
```java
element.getManager().isInProject(element) || 
ScratchUtil.isScratch(virtualFile) || 
containingFile.getViewProvider().getVirtualFile().getFileSystem() instanceof NonPhysicalFileSystem;
```
check

Support 'Send to FSI' action for 'no index' F# files

---

ReSharper.FSharp/src/FSharp/FSharp.TypeProviders.Protocol/src/Models/ProxyProvidedTypeWithContext.cs
rider-fsharp/testData/solutions/TypeProviderLibrary/TypeProviderLibrary/ProvidersErrors.fs
rider-fsharp/testData/typeProviders/GenerativeTypeProvidersTest/change abbreviation/gold/change abbreviation.gold
rider-fsharp/testData/typeProviders/TypeProvidersCacheTest/checkCachesWhenProjectReloading/gold/checkCachesWhenProjectReloading_after.gold
rider-fsharp/testData/typeProviders/TypeProvidersCacheTest/checkCachesWhenProjectReloading/gold/checkCachesWhenProjectReloading_before.gold
rider-fsharp/testData/typeProviders/TypeProvidersCacheTest/invalidation/gold/invalidation_after.gold
rider-fsharp/testData/typeProviders/TypeProvidersCacheTest/invalidation/gold/invalidation_before.gold
rider-fsharp/testData/typeProviders/TypeProvidersCacheTest/projectsWithEqualProviders/gold/projectsWithEqualProviders.gold
rider-fsharp/testData/typeProviders/TypeProvidersCacheTest/typing/gold/typing.gold

Fix for https://youtrack.jetbrains.com/issue/RIDER-106899/YamlConfig-instance-type-detected-as-incompatible-with-itself-when-in-a-function-in-another-file

Type Providers: recreate generative provided type instead of return stale

---

rider-fsharp/src/main/java/com/jetbrains/rider/ideaInterop/fileTypes/fsharp/highlighting/FSharpSyntaxHighlighterFactory.kt
rider-fsharp/src/main/java/com/jetbrains/rider/plugins/fsharp/services/fsi/FsiInputOutputProcessor.kt

F# Interactive: fix output syntax highlighting

---

ReSharper.FSharp/src/FSharp/FSharp.Psi/src/Annotations/FSharpExternalAnnotationsFileProvider.cs
rider-fsharp/src/test/kotlin/com/jetbrains/rider/plugins/fsharp/test/cases/markup/injections/FSharpLanguageInjectionTest.kt

Fix for https://youtrack.jetbrains.com/issue/RIDER-102632
There is a problem with the folder structure in the Rider bundle, and it is unclear when it can be fixed, so this PR suggests manually specifying the path to external annotations for the plugin.

Language injections: fix F# external annotations detection for the Rider bundle

---

.github/workflows/ci.yml
ReSharper.FSharp/GitHubActions.targets
ReSharper.FSharp/global.json
ReSharper.FSharp/test/src/FSharp.Tests/FSharpCompletionTest.fs

Fix GitHub Actions 

---

ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Analyzers/RecordExprAnalyzer.fs
ReSharper.FSharp/test/data/features/daemon/recordExprAnalyzer/Availability.fs
ReSharper.FSharp/test/data/features/daemon/recordExprAnalyzer/Availability.fs.gold
ReSharper.FSharp/test/data/features/quickFixes/useNestedRecordFieldSyntaxFix/File scoped.fs
ReSharper.FSharp/test/data/features/quickFixes/useNestedRecordFieldSyntaxFix/File scoped.fs.gold

Note: assignment expression still should be a single line

NestedRecordUpdate: support multiline records

---

ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/FSharp.Psi.Daemon.fsproj
ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Highlightings/FSharpTypeHintBulbActionsProvider.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Highlightings/TypeHintHighlighting.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Stages/PatternTypeHintsStage.fs

Actions available via the right-click on an inlay hint

Inlay Hints: Add bulb actions for type hints

---

ReSharper.FSharp/src/FSharp/FSharp.Psi.Intentions/src/Intentions/FunctionAnnotationAction.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 01 - Tuple.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 06 - Tuple with as 01.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 06 - Tuple with as 01.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 07 - Tuple with as 02.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 07 - Tuple with as 02.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 08 - Tuple with as 03.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 08 - Tuple with as 03.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 09 - Nested tuple 01.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 09 - Nested tuple 01.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 10 - Nested tuple 02.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 10 - Nested tuple 02.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 11 - Active pattern 01.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 11 - Active pattern 01.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 12 - Active pattern 02.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 12 - Active pattern 02.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/Let bindings - Tuples 01.fs
ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Intentions/SpecifyTypesTest.fs

Fix for [RIDER-119806](https://youtrack.jetbrains.com/issue/RIDER-119806/F-annotate-fails-for-a-function-with-tuples)
It is also consistent with parameter info (and xml docs) now

FunctionAnnotationAction: improvements for top-level tuple patterns

---

ReSharper.FSharp/src/FSharp/FSharp.Psi.Services/src/Daemon/Highlightings/FSharpErrorUtil.fs
ReSharper.FSharp/test/data/features/quickFixes/addParensToTypedLikeExpr/Availability 02.fs.gold
ReSharper.FSharp/test/data/features/quickFixes/addParensToTypedLikeExpr/Text - Type cast.fs.gold
ReSharper.FSharp/test/data/features/quickFixes/addParensToTypedLikeExpr/Text - Type test.fs.gold

getExprPresentableName: fix grammar

---

ReSharper.FSharp/src/FSharp/FSharp.Common/Resources/Strings.Designer.fs
ReSharper.FSharp/src/FSharp/FSharp.Common/Resources/Strings.resx
ReSharper.FSharp/src/FSharp/FSharp.Common/src/Settings/FSharpOptions.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/Resources/Strings.Designer.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/Resources/Strings.resx
ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Highlightings/FSharpTypeHintBulbActionsProvider.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Options/FSharpTypeHintOptionsPage.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Stages/PatternTypeHintsStage.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Services/src/Util/FSharpPatternUtil.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Services/src/Util/TypeAnnotationsUtil.fs
ReSharper.FSharp/test/data/features/daemon/typeHints/Patterns 02 - Other.fs
ReSharper.FSharp/test/data/features/daemon/typeHints/Patterns 02 - Other.fs.gold
ReSharper.FSharp/test/data/features/daemon/typeHints/Settings 01 - Show all.fs.gold
ReSharper.FSharp/test/data/features/daemon/typeHints/Settings 02 - Top level.fs.gold
ReSharper.FSharp/test/data/features/daemon/typeHints/Settings 03 - Locals.fs.gold
ReSharper.FSharp/test/data/features/daemon/typeHints/Settings 05 - Disabled 02 - By mode.fs.gold
ReSharper.FSharp/test/data/features/daemon/typeHints/Settings 06 - Other patterns.fs.gold
ReSharper.FSharp/test/data/features/daemon/typeHints/Unfinished declarations and expressions 01.fs
ReSharper.FSharp/test/data/features/daemon/typeHints/Unfinished declarations and expressions 01.fs.gold
ReSharper.FSharp/test/data/features/daemon/typeHints/_SettingsTestSource.fs
ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Daemon/TypeHintStageTest.fs

Inlay hints/PatternTypeHintsStage: support other patterns

---

ReSharper.FSharp/src/FSharp/FSharp.Common/src/ProjectModel/FSharpLanguageLevelProvider.fs
ReSharper.FSharp/src/FSharp/FSharp.Common/src/ProjectModel/FSharpLanguageVersion.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Daemon/src/Analyzers/LambdaAnalyzer.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Intentions/src/QuickFixes/ReplaceLambdaWithDotLambdaFix.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Services/src/Util/FSharpParensUtil.fs

Relax language level constraint for [RIDER-102956](https://youtrack.jetbrains.com/issue/RIDER-102956/Change-Replace-with-shorthand-lambda-refactoring-to-also-remove-parentheses) and [RIDER-122888](https://youtrack.jetbrains.com/issue/RIDER-122888/Missing-to-dot-lambda-CA)

FSharpLanguageLevel: support F#8 with patches

---

ReSharper.FSharp/src/FSharp/FSharp.Psi.Intentions/src/Intentions/FunctionAnnotationAction.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 13 - With attribute 01.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 13 - With attribute 01.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 14 - With attribute 02.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 14 - With attribute 02.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 15 - With attribute 03.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 15 - With attribute 03.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 16 - With attribute 04.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Function - Parameters - Pattern 16 - With attribute 04.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/Let bindings - Module 01.fs
ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Intentions/SpecifyTypesTest.fs

`TypedPat` is nested in `AttributePat`, what is currently ignored in `SpecifyTypes` -- so a wrong tree is produced, and also action is available even when a pattern with attribute is typed. The `AssertCorrectTreeStructure` attribute for tests is also very useful.

SpecifyTypes: fix for attributed parameter

---

ReSharper.FSharp/src/FSharp/FSharp.Common/src/Util/FSharpGlobalUtil.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Intentions/src/Intentions/DataProviders.fs
ReSharper.FSharp/src/FSharp/FSharp.Psi.Intentions/src/Intentions/FunctionAnnotationAction.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 01 - Method.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 01 - Method.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 02 - Property.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 02 - Property.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 03 - Method - Param groups.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 03 - Method - Param groups.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 04 - Extension 01.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 04 - Extension 01.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 05 - Extension 02.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 05 - Extension 02.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 06 - Optional param.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 06 - Optional param.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 07 - Optional param - With attribute.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Member 07 - Optional param - With attribute.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Pattern 01.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Pattern 01.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Pattern 02 - Optional.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/Pattern 02 - Optional.fs.gold
ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/Class - member - 01.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/Let bindings - Expr 01.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/Let bindings - Module 01.fs
ReSharper.FSharp/test/data/features/intentions/specifyTypes/availability/Patterns - 01.fs
ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Intentions/SpecifyTypesTest.fs

Additional entry point for `specify types` via context actions. Currently supported the same scenarios as for inlay hints materialization.
The following PR's will add support for primary constructors / properties with accessors, etc

Specify Types: support named patterns and members

---

ReSharper.FSharp/src/FSharp/FSharp.Psi/src/Impl/FSharpArgumentsOwnerUtil.cs
ReSharper.FSharp/test/data/features/daemon/regexp/Detection 04.fs
ReSharper.FSharp/test/data/features/daemon/regexp/Detection 04.fs.gold
ReSharper.FSharp/test/src/FSharp.Intentions.Tests/src/Daemon/RegexpHighlightingTest.fs

Fix for [RIDER-125426](https://youtrack.jetbrains.com/issue/RIDER-125426/Regex-is-not-highlighted-in-attributes-if-other-properties-are-set)

FSharpArgumentsOwnerUtil: fix for property initializers

---

ReSharper.FSharp/src/FSharp/FSharp.Psi.Intentions/src/QuickFixes/ReplaceLambdaWithDotLambdaFix.fs
ReSharper.FSharp/test/data/features/quickFixes/useDotLambdaSyntaxFix/File scoped - Remove parens.fs.gold
ReSharper.FSharp/test/data/features/quickFixes/useDotLambdaSyntaxFix/File scoped.fs.gold

The logic is changed back to how it was before a recent formatter update.

UseDotLambdaSyntaxFix: remove redundant parens (fix)
